name: swiss-rental
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - lightgbm
  - category_encoders
  - optuna
  - shap
  - plotly
  - streamlit          
  - jupyterlab
  - ipykernel
  - tqdm
  - joblib
  - scipy